### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by danielbonnell** [jaimeiniesta/metainspector#217] opened 2017-09-29 00:39 UTC
Hi, I'm getting an error when trying to scrape certain `ow.ly` urls. I'm not really familiar with the inner workings of this gem, I just use it for a project that I work on. I'm not sure if the problem is with this gem or `net/http` or `faraday`.

Running the following code with the latest release yields the following error:
```

url = 'http://ow.ly/Z4ye308JPwc'
=> "http://ow.ly/Z4ye308JPwc"
irb(main):008:0> page = MetaInspector.new(url, connection_timeout: 5, read_timeout: 3, retries: 2, download_images: true, faraday_options: { ssl: { verify: false } })
NoMethodError: undefined method `+' for nil:NilClass
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/scout_apm_ruby-461b953bc12d/lib/scout_apm/instruments/net_http.rb:33:in `request_scout_description'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/scout_apm_ruby-461b953bc12d/lib/scout_apm/instruments/net_http.rb:25:in `request_with_scout_instruments'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:85:in `block in perform_with_redirection'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:80:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:85:in `block in perform_with_redirection'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:80:in `perform_with_redirection'
... 11 levels...
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:51:in `fetch'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:41:in `response'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector/request.rb:25:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector/document.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector/document.rb:32:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector.rb:20:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/metainspector-5.4.1/lib/meta_inspector.rb:20:in `new'
	from (irb):8
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'irb(main):009:0> [Scout] [09/29/17 00:34:27 +0000 run.8100 (4)] INFO : [00:32] Delivering 2 Metrics for 0 requests and 0 Slow Transaction Tr
```

**Comment by jaimeiniesta** [comment] 2017-09-29 11:00
Thanks for the bug report!

It seems that the problem is within faraday or net/http indeed. Will investigate when I have some time, feel free to send them a PR :)

**Comment by johncip** [comment] 2018-06-12 01:22
I found this on google after running into the same issue. I think the problem is that Scout monkey-patches Net::HTTP in a way that incorrectly assumes `@address` is non-null.

**Comment by jaimeiniesta** [comment] 2018-06-13 10:55
@johncip thanks for the report! PRs are more than welcome :)

**Comment by jaimeiniesta** [comment] 2018-09-27 15:06
@danielbonnell I just tried your example with MetaInspector 5.6.0 and I no longer get this exception. I'll close this issue, feel free to reopen if you can reproduce it again.

**Closed by jaimeiniesta** 2018-09-27 15:06 UTC

**Comment by danielbonnell** [comment] 2018-09-27 15:20
I can confirm that it's working now (with that exact same link) in the 5.6.0. Weird. Thanks!
