### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by alfie-max** [jaimeiniesta/metainspector#190] opened 2016-09-10 18:48 UTC
Rails 4.2.7.1
Ruby 2.3.1
metainspector (5.3.0)

```
Loading development environment (Rails 4.2.7.1)
>> domain = 'revenew.com'
"revenew.com"
>> MetaInspector.new(domain).to_hash
ArgumentError: invalid byte sequence in UTF-8
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/request.rb:32:in `tr'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/request.rb:32:in `read'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/document.rb:105:in `document'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/document.rb:78:in `to_s'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/parser.rb:33:in `parsed'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/parser.rb:20:in `initialize'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/document.rb:39:in `new'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector/document.rb:39:in `initialize'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector.rb:20:in `new'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/metainspector-5.3.0/lib/meta_inspector.rb:20:in `new'
	from (irb):2
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/alfie/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by jaimeiniesta** [comment] 2016-09-19 16:50
Duplicate of #191

**Closed by jaimeiniesta** 2016-09-19 16:50 UTC
