### ISSUE TITLE
help please. My code does nothing on after_save callback on model

### ISSUE THREAD

**Issue by pmaojo** [jaimeiniesta/metainspector#207] opened 2017-04-11 18:25 UTC
This is in a Model, I want the script to save the al:ios:url of a facebook page.
 I don´t get error, but the data is not saved, don´t know what could be the problem?
```

  after_save :facebookapplink

private

  def facebookapplink
    if !self.mobileurl
      unless !self.facebook
        urlfb = self.facebook
        fb = MetaInspector.new(urlfb, :headers => {'User-Agent' => 'Mozilla/5.0'}, :connection_timeout => 6, :read_timeout => 2, :retries => 4)
        url = fb.meta_tags['property']['al:ios:url']
        if url != nil
          self.update_column(:mobileurl, url)
        end
      end
    end
  end
```

**Comment by jaimeiniesta** [comment] 2017-04-11 20:56
Hello, I'm afraid we can't help you here if the problem is not directly in Metainspector, but let's give it a try. In this part of the code:

```ruby
MetaInspector.new(urlfb, :headers => {'User-Agent' => 'Mozilla/5.0'}, :connection_timeout => 6, :read_timeout => 2, :retries => 4)
```

What is the URL in `urlfb`? We need an URL to test with, and if you think there's a bug, the expected result and the actual result.

Thanks!

**Comment by pmaojo** [comment] 2017-04-12 11:53
A very similar function is working on my computer running `ruby nameofile.rb` 

```
require 'metainspector'
a = Time.now
urlfb = 'https://www.facebook.com/pulpomarketing'
fb = MetaInspector.new(urlfb, :connection_timeout => 10, :read_timeout => 5, :retries => 4, :headers => {'User-Agent' => 'Mozilla 5.0'})
url = fb.meta_tags['property']['al:ios:url']
if url != nil
  puts url
else 
  puts 'nil'
end
b = Time.now - a
puts b * 1000.000

```

**Comment by jaimeiniesta** [comment] 2017-04-12 12:11
Then I guess the problem is in your app, not in Metainspector?

**Comment by jaimeiniesta** [comment] 2017-04-14 15:28
Just tested the code in your second comment, and it returns `fb://page/?id=597480420275501` - which is the value for that meta tag in this page.

Closing this, feel free to reopen if you think there's any bug.

**Closed by jaimeiniesta** 2017-04-14 15:28 UTC
