### ISSUE TITLE
linkedin.com profile pages are not getting scraped.

### ISSUE THREAD

**Issue by cgarre** [jaimeiniesta/metainspector#249] opened 2019-06-29 06:31 UTC
linkedin.com/in/williamhgates  - for example. 
doesnt get description, title or image.

**Comment by jaimeiniesta** [comment] 2019-07-01 10:05
Duplicate of https://github.com/jaimeiniesta/metainspector/issues/209

**Closed by jaimeiniesta** 2019-07-01 10:05 UTC
