### ISSUE TITLE
Garbled descriptions returned when scraping JPG urls

### ISSUE THREAD

**Issue by trotzig** [jaimeiniesta/metainspector#168] opened 2016-01-22 11:25 UTC
I'm trying to figure out why scraping image URLs sometimes results in garbled descriptions. These for example:
https://cnngps.files.wordpress.com/2011/12/putin.jpg
https://shechive.files.wordpress.com/2016/01/these-skyline-rings-will-help-you-declare-your-love-for-cities-all-around-the-world-4.jpg

For some reason, this image is okay (no description returned):
http://i2.cdn.turner.com/cnn/dam/assets/140603171912-obama-waves-story-top.jpg

Here's an example of what is returned (tested using https://metainspectordemo.herokuapp.com):
```
Description
ù¿ç­*Ú=3 ÁñQvî6Yi§cÎ6­ä;ôv7XÐAüßÍYtPý2á¡ëlZ8ípaæ»°3´ÿ hØÏF9ã"çðÝðÜßúµZë®ÜI-ÐnÚå/ElÞè!Ì§hÖÿ ÐU®cwìk®wùEîÜ3¢ØX:÷LÏæò~>ß¢÷np¾"dcAccKÝ\ÚÇ»¿7r¨ïÒ:Æ¿ÚxòâfTuÍ`¯­Ó´ímÛës|ÿ ­¬\_Lk¿oc`²çêËµÐê5§^Ab¤S'-bTJQ))b¢TJJÿÐëBà:Ý?ë?Pª£º£êÛK¾kÏ´þw¹wás_]:cnû7P­¿¦cXGq½û;.­V#FÆ)T¼ÃÆ]avFðIõ!ÎæIüéýÝë®e-öX¸ø_ºÍß£­Ì Iwæÿ ×.¦ osÚdFXÇRáký LêcU¥]øµÔ×9ïÌ®_ªSn3¥µãWãù+6·däV6òfNçk±çZajÈ{³Õq`«ÕÏò èëh5ï:¼Ã¨Ñ~HfC.pÝ«FØþS«s¼U¬\ÛjsèLèê¤ááZ2^ô_Lý¶íHLxþ*gÖ¼\vg¹Æ\ýûq:]nNÚëËÿ fç,.wP½­µXßôMäù¼½Ìc?ë¯HjÛG©ÇúàË²¢ÓíáÛóVµYùMeäl~¥¼ÇòC¿¸úH®êÚïç}ûÙüâì>­c_^+ý]	!ÛGÃÜßë&Î -¾¶ç2Ýi ~ÛIqä6ÃúxþW¦ÅÞ¾7ã²Ãé8.c+%ãÙY&±æáµ¯ÿ 5ï[«2mÆbTJLSØØÅH¨Ä¨"¤§ÿÑëB­Õ1Ó®¢¢[t(pä[_¾¿ó¿þÚ°ÚH29UÙ­_]5íÇ{ÃÔ zÕG³ó|°×ß§oªý]ËÈ¹ÎÁe72ÒKkµÞªs¯-sl«Ðÿ Zärw¶ÂN¬¼xû]ÿ R£1=["`êÑë©Ã£2¸;o¶9Y¶bdb\X×³PÑ0à}ºþç*bÚ`6w64þ+l_ÔïqÔ·ÇÄîÿ ¥íN¨ë³ö1ÙÓXc^és¢gkê;sÿ wØ z5n°¶ ;»¹õkZ}JkAý!%îÿ 3_nA`5Òóæ?Ü)è OgC#¦²þG,k,ÑÍ1Ã}?ûòÇco¢öÓQªY'a­ÿ G k}Û¿1uf0@hK#Í-ÿ ©YYXf ·´9Íú/#VäîÚÖ4®ÓëjipÆ°Ýæ>¨æ±¾Æÿ )ëZÁM,±ñ×_õ-³zmöÀ7ø©×n¸T×nq>ÿ "H]þr(§ Àoèf£y 4ö é»Þ¬(±®c]¿:8û©ÊxÐ¼ÈbD¢NTJJX¨å1IOÿÒëp¢{6+úÅèu¼Öíu¥ãá`m¿÷õß¹?®¸¦¼Ì|à?GÏEçÂÚ½Ìÿ ·(wþ -1WÎ×KlµÍánôXÜ!ÀsçýUX xx

URL
https://cnngps.files.wordpress.com/2011/12/putin.jpg

Scheme
https

Host
cnngps.files.wordpress.com

Root URL
https://cnngps.files.wordpress.com/
```
https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fcnngps.files.wordpress.com%2F2011%2F12%2Fputin.jpg

**Comment by jaimeiniesta** [comment] 2016-01-22 11:27
It makes no sense to scrape an image, MetaInspector is aimed at scraping HTML only.

**Comment by trotzig** [comment] 2016-01-22 11:35
Yeah, i just saw the part about `html_content_only` in the docs.
https://github.com/jaimeiniesta/metainspector#html-content-only

I ended up here because we use MetaInspector to scrape whatever URLs people add when writing comments. And sometimes those are in fact images. While I agree that we could probably avoid scraping if we think it's an image, wouldn't it make sense for MetaInspector to do something better by default? Knowing if an URL is an image beforehand is sometimes impossible (it's not until we have actually looked at the response headers until we know).

**Comment by trotzig** [comment] 2016-01-22 11:35
Thanks for the quick reply by the way!

**Comment by jaimeiniesta** [comment] 2016-01-22 11:41
Ah, thanks for the explanation!

Yes, we should probably change this default, let me think about it (or submit a PR if you wish).

**Comment by trotzig** [comment] 2016-01-22 11:48
I'll give it a try.

**Comment by jaimeiniesta** [comment] 2016-01-22 11:58
Cool :)

I've just updated the demo so it raises an exception when the returned content is not HTML.

Your opinion here as a user of MetaInspector is really valuable, let me know what you think we should do with this option. Should we enable it by default? Or maybe completely remove it so it's no longer an option?

**Comment by trotzig** [comment] 2016-01-22 13:39
It's tricky, I understand that. The commit I made fixes things for images, but other content types aren't handled. It would be a pain to add exceptions in the code for all different kinds. I wonder if a whitelist of some sort can be used, and then users can override that whitelist? By default it could be 

```ruby
allowed_content_types: [
  /^text\/\w+$/,
  /^image\/w+$/+
]
```

Any content type not in this list would result in an error thrown.

**Comment by jaimeiniesta** [comment] 2016-02-01 11:03
Closing this as on [this PR discussion](https://github.com/jaimeiniesta/metainspector/pull/169) we've seen this is not a bug, but a feature :)

**Closed by jaimeiniesta** 2016-02-01 11:03 UTC
