### ISSUE TITLE
MetaInspector behaving differently on local when comparing to demo site

### ISSUE THREAD

**Issue by ronniekessler** [jaimeiniesta/metainspector#225] opened 2018-03-07 22:43 UTC
I ran a url through the demo site (https://metainspectordemo.herokuapp.com/) and got the correct page.images.best but when I run locally (with same version of gem) I get a different 'best' image.

Any thoughts on why this would happen?

Apologies, I can't provide the url for client privacy reasons.

**Comment by jaimeiniesta** [comment] 2018-03-08 10:29
It would be good if you could provide a demo site that reproduces this error. I understand you can't post your client's URL, but maybe you can craft a little site somewhere else that reproduces it, or find another URL out there where this also happens.

Without that, it's very difficult to reproduce the issue.

**Comment by jaimeiniesta** [comment] 2018-03-27 10:01
@ronniekessler closing this issue as we can't reproduce it, feel free to reopen when you can provide an example.

**Closed by jaimeiniesta** 2018-03-27 10:01 UTC

**Comment by malav1410** [comment] 2018-04-10 10:34
Same issue here..
I am getting title, image and everything on my development version but same link not giving any result on metainspectordemo site.

url: https://www.linkedin.com/pulse/20140830162720-155900101-why-do-professional-athletes-need-a-coach
